### ISSUE TITLE
startwifi suggestion

### ISSUE THREAD

**Issue by GearlooseTechnology** [adojang/Weave#1]
Hi,

I really like this initiative. I use a similar structure for custom smart devices. Yours is more extensive with the dash, so I might consider switching.
In my situation, there are lots of AP's and SSID's. Sometimes I noticed that they keep on trying to connect with unlogical AP's that don't necessarily provide the best connection. To save some pain you may want to add the following to the "startwifi -> STA" section before connecting.

```
WiFi.setScanMethod(WIFI_ALL_CHANNEL_SCAN);
WiFi.setSortMethod(WIFI_CONNECT_AP_BY_SIGNAL);
```

Thanks a lot, great work.

**Comment by adojang** [comment]
Hey! Thanks for the suggestion. I've made the changes. Glad you're finding it useful :)
