### ISSUE TITLE
Does not compile when directly using PlatformIO's built in library manager

### ISSUE THREAD

**Issue by adojang** [adojang/Weave#2]
There's a mbedl_5 kind of error which relates to an old library that hasn't been updated.
The workaround is to just directly download and place this library in your /lib folder.

**Comment by GearlooseTechnology** [comment]
It has been fixed, however there is an issue with getting the latest version using PlatformIO repository. If you put 

`
lib_deps =
https://github.com/me-no-dev/ESPAsyncWebServer.git
`

in the platformio.ini I believe it will work.

**Comment by adojang** [comment]
Thank you!
